import { escape as e } from './security.js';
export { adminPage } from './admin-view.js';

export const categories={'lesson-report':'Lesson Report',notice:'お知らせ','word-rhythm':'Word Rhythm'};
const a=name=>'/assets/'+name;
export const assets={
  ladybird:a('f00f2c_1b7349ff3b904af8b19f908a04844cc2~mv2.png'),
  smallLadybird:a('f00f2c_949466f73c8e46fc9ece2b2065c8d0ce~mv2.png'),
  logo:a('f00f2c_c0145bc6080743e7a7695e3f33b03725~mv2.png'),
  ribbon:a('f00f2c_6e129edf63c84006888b494e5a157374~mv2.png'),
  staple:a('41d000_371177fb8c20d34b349cc6c2cab2f1ca.png'),
  slides:['f00f2c_94b4bc10dfd043d6b23e26f9172b1142~mv2_d_2775_1954_s_2.jpg','f00f2c_c6870631063643fba912f832fef08f2e~mv2_d_2592_1502_s_2.jpg','f00f2c_05a5e5694cf64b1e8efe487e8907cf6a~mv2.png','f00f2c_69e114b228074228ac335198c18645a5~mv2.jpg','f00f2c_ca657c8ac8954fdc812233328e4f6dd1~mv2_d_3000_2250_s_2.jpg','f00f2c_6ea57b99f64f4bc2a31af6cc18f39540~mv2.jpg'].map(a),
  gallery:['f00f2c_a8b412b077c448f0b0b9412851e5a8dd~mv2_d_3264_2448_s_4_2.jpg','f00f2c_81692d5c0453453f9992cbe2540ef308~mv2_d_2351_1631_s_2.jpg','f00f2c_b609fdfad74f47cfbaaa5f84a434f641~mv2.jpg','f00f2c_d7d12903434247f58b18144e74a15238~mv2_d_3628_2483_s_4_2.jpg','f00f2c_76231a0230274d72811983925082b570~mv2.jpg','f00f2c_397b67b26cc541888a993b200f106a2f~mv2_d_2650_1846_s_2.jpg','f00f2c_0e3494edf3c74f45b8c57a5269112073~mv2_d_2206_1899_s_2.png','f00f2c_6da47962557448b8bb85836cebcb02eb~mv2_d_3264_2448_s_4_2.jpg','f00f2c_8d2263a8704049fcb1956c80a804b976~mv2.jpg'].map(a)
};
const date=value=>value?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'long',day:'numeric'}).format(new Date(value)):'';
export function page({title,body,route='',user=null,noindex=false}) {
  const nav=[['/','Home'],['/classes','Course & Price'],['/gallery','Gallery'],['/access','Access'],['/parents','Parents']];
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}${route==='/'?'':' | SMALL WORLD'}</title><meta name="description" content="東京都府中市のこども英語教室 SMALL WORLD。英語を生き生きと豊かに学ぶ。英会話・音楽・フォニックス・英検。">${noindex?'<meta name="robots" content="noindex,nofollow">':''}<link rel="icon" href="${assets.smallLadybird}" type="image/png"><link rel="preload" href="/assets/chelsea-market.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script></head><body><a class="skip" href="#main">メインコンテンツへ</a><div class="site-shell"><header class="site-header"><nav aria-label="サイト"><button class="mobile-menu" aria-expanded="false" aria-controls="main-nav">☰ <span>Menu</span></button><ul id="main-nav">${nav.map(([url,label])=>`<li${url==='/parents'?' class="has-submenu"':''}><a href="${url}"${route===url?' aria-current="page"':''}>${label}</a>${url==='/parents'?'<ul class="submenu"><li><a href="/blog">News & Reports</a></li></ul>':''}</li>`).join('')}</ul></nav><a class="login-link" href="${user?.role==='admin'?'/admin':user?'/parents':'/login'}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="12" fill="currentColor"/><circle cx="12" cy="8" r="4" fill="white"/><path d="M5 21v-3a7 7 0 0 1 14 0v3" fill="white"/></svg>${user?e(user.name):'ログイン'}</a><div class="hero" aria-label="教室の風景"><div class="slides">${assets.slides.map((src,i)=>`<img class="slide${i===0?' active':''}" src="${src}" alt="SMALL WORLDのレッスン風景 ${i+1}" width="960" height="337" ${i>0?'loading="lazy"':''}>`).join('')}</div><a class="brand" href="/" aria-label="SMALL WORLD ホーム"><img class="brand-logo" src="${assets.logo}" alt="SMALL WORLD" width="392" height="192"><img class="brand-ribbon" src="${assets.ribbon}" alt="こども英語" width="331" height="56"></a><a class="contact-pill" href="/contact">メール相談</a><img class="hero-ladybird" src="${assets.smallLadybird}" alt="" width="96" height="84"><div class="slide-controls"><button data-slide="prev" aria-label="前の写真">‹</button><button data-slide="pause" aria-label="スライドショーを一時停止">Ⅱ</button><button data-slide="next" aria-label="次の写真">›</button></div></div></header><main id="main" class="paper ${route==='/'?'home-paper':''}">${body}</main></div></body></html>`;
}
const staple=()=>`<img class="staple" src="${assets.staple}" alt="" width="57" height="12">`;
export function homePage(posts) {
  return `<h1 class="tagline">~英語を生き生きと豊かに学ぶ~</h1><section class="about"><img src="${assets.ladybird}" alt="SMALL WORLDのてんとう虫" width="164" height="144"><div><h2>About Us</h2><p>東京都府中市のこども英語教室。英会話や歌、英語リトミックはもちろん、独自の音声学のメソッドをベースにした音節やフォニックスの学習で美しい英語を学びます。<br>体系的に学ぶ英文法にも力を入れており、英検などの英語資格対策なども学習します。<br>生き生きと学び続けるため、豊かに学び続けるための英語教室です。</p></div></section><div class="home-lower"><aside class="open"><h2>Open</h2><ul><li>月曜日 16:25-19:00</li><li>木曜日 16:25-19:00</li><li>金曜日 16:25-19:00</li><li>日曜日 9:30-12:30 (月2回)</li></ul></aside><section class="home-news"><h2>News</h2>${posts.map(p=>`<article><h3><a href="/post/${encodeURIComponent(p.slug)}">${e(p.title)}</a></h3><div class="news-item">${p.cover?`<a href="/post/${encodeURIComponent(p.slug)}" tabindex="-1" aria-hidden="true"><img src="${e(p.cover)}" alt="" loading="lazy"></a>`:''}<p>${e(p.excerpt)}</p></div></article>`).join('')}</section></div><footer class="home-footer"><p>Tel ： <a href="tel:09060200512">090-6020-0512</a></p><a href="https://www.kokolit.com/" target="_blank" rel="noopener noreferrer">運営会社</a><small>© 2018 by SMALL WORLD</small></footer>`;
}
export function coursesPage() {return `<section class="courses"><h1>Course & Price</h1><p class="course-subtitle">コース＆月謝</p><table class="price-table"><caption class="sr-only">コースごとの月謝</caption><tbody><tr><th scope="row">75min x 週1回</th><td>¥9,900</td></tr><tr><th scope="row">75min x 週2回</th><td>¥14,100</td></tr><tr><th scope="row">75min x 週3回</th><td>¥16,830</td></tr><tr><th scope="row">120min x 月2回 <small>(日曜日)</small></th><td>¥9,240</td></tr></tbody></table><div class="price-notes"><p>※入会金 ¥6,600は2ヶ月目にいただきます。</p><p>※上記学費の他に、設備費·維持管理費·教材費として¥2,000/月いただきます。</p><p>（日曜日プランは1,5,9月に2,750円ずつをいただきます。）</p><p>※60minクラスもあります。その場合の月謝は¥7,920です。</p></div></section>`;}
export function galleryPage(){return `${staple()}<section class="gallery-page"><h1>Kids love to study at SMALL WORLD!</h1><div class="gallery-grid">${assets.gallery.map((src,i)=>`<button class="gallery-item" data-gallery="${i}" aria-label="写真 ${i+1} を拡大"><img src="${src}" alt="教室で楽しく学ぶ子どもたち ${i+1}" loading="lazy" width="282" height="282"></button>`).join('')}</div><dialog id="lightbox" aria-label="教室の写真"><button class="lightbox-close" aria-label="閉じる">×</button><button class="lightbox-prev" aria-label="前の写真">‹</button><img alt="教室の写真"><button class="lightbox-next" aria-label="次の写真">›</button><p class="lightbox-count"></p></dialog></section>`;}
export function accessPage(){return `${staple()}<section class="access-page"><h1>Access</h1><p class="school-address-heading">こども英語 SMALL WORLD　本町教室</p><address>東京都府中市本町2-12-17<br><a href="tel:09060200512">090-6020-0512</a></address><iframe class="map" title="SMALL WORLD 本町教室への地図" src="https://www.google.com/maps?q=35.6678576,139.4736536&z=16&hl=ja&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a class="map-link" href="https://www.google.com/maps/dir/?api=1&destination=35.6678576,139.4736536" target="_blank" rel="noopener noreferrer">Google マップで道順を見る</a></section>`;}
export function contactPage(csrf){return `${staple()}<section class="contact-page"><h1>Contact</h1><form class="contact-form" data-api-form="/api/contact"><input type="hidden" name="_csrf" value="${e(csrf)}"><label class="sr-only" for="name">Name *</label><input id="name" name="name" placeholder="Name *" autocomplete="name" required maxlength="100"><label class="sr-only" for="email">Email *</label><input id="email" name="email" placeholder="Email *" type="email" autocomplete="email" required maxlength="254"><label class="sr-only" for="subject">Subject</label><input id="subject" name="subject" placeholder="Subject" maxlength="200"><label class="sr-only" for="message">Message *</label><textarea id="message" name="message" placeholder="Message" required maxlength="10000"></textarea><div class="honey" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-status" role="status"></p><button type="submit">Send</button></form></section>`;}
export function loginPage(csrf,next){return `${staple()}<section class="account-page"><h1>Parents</h1><div class="account-card"><img src="${assets.smallLadybird}" alt="" width="60" height="52"><h2>${next==='/admin'?'管理者ログイン':'保護者ログイン'}</h2><p>Lesson Report・お知らせ・Word Rhythm を<br>こちらからご覧いただけます。</p><form data-api-form="/api/login"><input type="hidden" name="_csrf" value="${e(csrf)}"><input type="hidden" name="next" value="${e(next)}"><label for="login-email">メールアドレス</label><input id="login-email" name="email" type="email" autocomplete="username" required><label for="login-password">パスワード</label><input id="login-password" name="password" type="password" autocomplete="current-password" required maxlength="256"><p class="form-status" role="alert"></p><button class="primary-button" type="submit">ログイン</button></form><p class="account-help">初めての方・パスワードをお忘れの方は、<br><a href="/contact">教室へお問い合わせください。</a></p></div></section>`;}
export function invitePage(invite,raw,csrf){return `<section class="account-page"><h1>Welcome to SMALL WORLD</h1><div class="account-card"><h2>保護者アカウントの登録</h2><p>${e(invite.name)} 様<br>${e(invite.email)}</p><form data-api-form="/api/accept-invite"><input type="hidden" name="_csrf" value="${e(csrf)}"><input type="hidden" name="token" value="${e(raw)}"><label for="new-password">パスワード（12文字以上）</label><input id="new-password" name="password" type="password" minlength="12" maxlength="256" autocomplete="new-password" required><label for="confirm-password">パスワードを確認</label><input id="confirm-password" name="confirm_password" type="password" minlength="12" autocomplete="new-password" required><p class="form-status" role="alert"></p><button type="submit" class="primary-button">登録してログイン</button></form></div></section>`;}
const categoryPath=key=>'/blog/categories/'+(key==='notice'?encodeURIComponent('お知らせ'):key);
const card=p=>`<article class="blog-card">${p.cover?`<a href="/post/${encodeURIComponent(p.slug)}" tabindex="-1" aria-hidden="true"><img src="${e(p.cover)}" alt="" loading="lazy"></a>`:`<div class="card-symbol"><img src="${assets.smallLadybird}" alt=""></div>`}<div class="card-body"><span class="category-label">${categories[p.category]}</span>${p.published_at?`<time datetime="${e(p.published_at)}">${date(p.published_at)}</time>`:''}<h2><a href="/post/${encodeURIComponent(p.slug)}">${e(p.title)}</a></h2><p>${e(p.excerpt)}</p>${p.visibility==='members'?'<span class="member-label">保護者限定</span>':''}</div></article>`;
export function parentsPage(user,posts,csrf){return `${staple()}<section class="blog-section"><div class="page-heading"><h1>Parents</h1><button class="text-button" data-logout data-csrf="${e(csrf)}">ログアウト</button></div><p class="welcome">${e(user.name)} 様、こんにちは。</p><div class="parent-links">${Object.entries(categories).map(([key,label])=>`<a href="${categoryPath(key)}"><strong>${label}</strong><span>${key==='lesson-report'?'レッスンの様子':key==='notice'?'教室からのお知らせ':'おうちで英語とリズム'}</span><b aria-hidden="true">→</b></a>`).join('')}</div><div class="page-heading"><h2>News & Reports</h2><a href="/blog">すべての記事 →</a></div><div class="blog-grid">${posts.length?posts.map(card).join(''):'<p class="empty-state">新しい記事をお楽しみに。</p>'}</div>${user.role==='admin'?'<p class="admin-entry"><a href="/admin">管理画面を開く →</a></p>':''}</section>`;}
export function blogPage(posts,category,query,pageNumber,totalPages){const base=category?categoryPath(category):'/blog';return `${staple()}<section class="blog-section"><h1>News & Reports</h1><nav class="category-tabs" aria-label="記事の種類"><a href="/blog" ${!category?'aria-current="page"':''}>すべて</a>${Object.entries(categories).map(([key,label])=>`<a href="${categoryPath(key)}" ${category===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><form class="blog-search" method="get" action="${base}"><label class="sr-only" for="blog-search">記事を検索</label><input id="blog-search" name="q" value="${e(query)}" placeholder="記事を検索" maxlength="100"><button type="submit">検索</button></form><div class="blog-grid">${posts.length?posts.map(card).join(''):'<p class="empty-state">記事がありません。</p>'}</div>${totalPages>1?`<nav class="pagination" aria-label="ページ">${pageNumber>1?`<a href="${base}?page=${pageNumber-1}&q=${encodeURIComponent(query)}">← 前へ</a>`:''}<span>${pageNumber} / ${totalPages}</span>${pageNumber<totalPages?`<a href="${base}?page=${pageNumber+1}&q=${encodeURIComponent(query)}">次へ →</a>`:''}</nav>`:''}</section>`;}
export function postPage(post){return `<article class="post-page"><a class="back-link" href="/blog">← News & Reports</a>${post.status!=='published'?'<p class="draft-banner">プレビュー：この記事は公開されていません。</p>':''}<p class="post-meta"><a href="${categoryPath(post.category)}">${categories[post.category]}</a>${post.published_at?`<time datetime="${e(post.published_at)}">${date(post.published_at)}</time>`:''}${post.visibility==='members'?'<span>保護者限定</span>':''}</p><h1>${e(post.title)}</h1>${post.lesson_date||post.class_name?`<p class="lesson-details">${e(post.lesson_date)} ${e(post.class_name)}</p>`:''}${post.cover?`<img class="post-cover" src="${e(post.cover)}" alt="${e(post.title)}">`:''}<div class="post-content">${post.body}</div></article>`;}
export function messagePage(title,message,link='/'){return `<section class="message-page"><h1>${e(title)}</h1><p>${e(message)}</p><a class="primary-button" href="${e(link)}">${link==='/parents'?'保護者ページへ':'ホームに戻る'}</a></section>`;}
